### ISSUE TITLE
Support for Relay 12 via relay-hooks v6

### ISSUE THREAD

**Issue by matt-dalton** [morrys/react-relay-offline#101]
Hi @morrys. I'm sure you're on it, but I'm getting an error when using Relay v12:

```
getSourceForActor is not a function
```

I noticed relay-hooks has recently released an [update supporting v12](https://github.com/relay-tools/relay-hooks/releases/tag/v6.0.0) - would it be straightforward to update this lib to use that version?

**Comment by morrys** [comment]
Hi @matt-dalton,
my next step is to update react-relay-offline in order to use relay-hooks 6.0 and adapt it to relay V12.

I didn't have time to look at it yet as I've been engaged in relay-hooks (and real work).

As soon as I have news I will update the issue.

However, that error does not seem related to my library.

**Comment by morrys** [comment]
Hi @matt-dalton,
from a first check, in relay v12, they changed the store again and that's why you got that error.

Relay v12 support will take longer than expected.

**Comment by morrys** [comment]
Here the PR in draft: https://github.com/morrys/wora/pull/108

**Comment by morrys** [comment]
released with react-relay-offline 5.0.0 https://github.com/morrys/react-relay-offline/releases/tag/v5.0.0
